bold = true
color_mode = "rgb" # ansi, rgb or none
palette = "default" # default, darker, pastel or matrix
rainbow = 2 # 0-255
delay_ms = 20
inherit_style = false
kinds = ["curved"] # heavy, light, curved, knobby, emoji, outline, dots, blocks, sus
num_pipes = 3
reset_threshold = 0.6 # 0.0–1.0
turn_chance = 0.20 # 0.0–1.0

