add_newline = false

format='''
[‚ï≠](bold purple)[{](fg:#ff00ff) $all[}](fg:#ff00ff)
[‚ï∞‚îÑ$character](bold purple)
'''

continuation_prompt = '‚ñ∂‚ñ∂ '

right_format='''$username@$os $time'''

[character]
format = '$symbol '
# success_symbol = "[‚ùØ](bold green)"
# error_symbol = "[X](bold red)"
error_symbol = "[Œª](bold #ff5555)"
success_symbol = "[Œª](bold #50fa7b)"

[line_break]
disabled = true

[aws]
symbol = "aws "
format = '\([$symbol($profile)(\($region\))(\($duration\))]($style)\) '
style = "bold #ffb86c"

[azure]
symbol = "azure "

[bun]
symbol = "bun "
format = '\([$symbol($version)]($style)\) '

[c]
symbol = "C "
format = '\([$symbol($version(-$name))]($style)\) '

[cmake]
symbol = "cmake "
format = '\([$symbol($version)]($style)\) '

[cobol]
symbol = "cobol "
format = '\([$symbol($version)]($style)\) '

[conda]
symbol = "conda "
format = '\([$symbol$environment]($style)\) '

[crystal]
symbol = "crystal "
format = '\([$symbol($version)]($style)\) '

[daml]
symbol = "daml "
format = '\([$symbol($version)]($style)\) '

[dart]
symbol = "dart "
format = '\([$symbol($version)]($style)\) '

[deno]
symbol = "deno "
format = '\([$symbol($version)]($style)\) '

[dotnet]
symbol = ".NET "
format = '\([$symbol($version)(üéØ $tfm)]($style)\) '

[directory]
read_only = " read only"
format = '\[[$path]($style)[$read_only]($read_only_style)\] '
style = "bold #50fa7b"

[docker_context]
symbol = "docker "
format = '\([$symbol$context]($style)\) '

[elixir]
symbol = "elixir "
format = '\([$symbol($version \(OTP $otp_version\))]($style)\) '

[elm]
symbol = "elm "
format = '\([$symbol($version)]($style)\) '

[erlang]
symbol = "erlang "
format = '\([$symbol($version)]($style)\) '

[fennel]
symbol = "fennel "
format = '\([$symbol($version)]($style)\) '

[fossil_branch]
symbol = "fossil "
format = '\([$symbol$branch]($style)\) '

[gcloud]
symbol = "gcp "
format = '\([$symbol$account(@$domain)(\($region\))]($style)\) '

[git_branch]
symbol = "git "
format = '\[[$symbol$branch]($style)\] '
style = "bold #ff79c6"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '
style = "bold #ff5555"

[golang]
symbol = "go "
format = '\([$symbol($version)]($style)\) '

[gradle]
symbol = "gradle "
format = '\([$symbol($version)]($style)\) '

[guix_shell]
symbol = "guix "
format = '\([$symbol]($style)\) '

[haskell]
symbol = "haskell "
format = '\([$symbol($version)]($style)\) '

[haxe]
symbol = "haxe"
format = '\([$symbol($version)]($style)\) '

[helm]
symbol = "helm "
format = '\([$symbol($version)]($style)\) '

[hg_branch]
symbol = "hg "
format = '\([$symbol$branch]($style)\) '

[java]
symbol = "java "
format = '\([$symbol($version)]($style)\) '

[julia]
symbol = "julia "
format = '\([$symbol($version)]($style)\) '

[kotlin]
symbol = "kotlin "
format = '\([$symbol($version)]($style)\) '

[lua]
symbol = "lua "
format = '\([$symbol($version)]($style)\) '

[nodejs]
symbol = "nodejs "
format = '\([$symbol($version)]($style)\) '

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "
format = '\([$symbol$project]($style)\) '

[nim]
symbol = "nim "
format = '\([$symbol($version)]($style)\) '

[nix_shell]
symbol = "nix "
format = '\([$symbol$state( \($name\))]($style)\) '

[ocaml]
symbol = "ocaml "
format = '\([$symbol($version)(\($switch_indicator$switch_name\))]($style)\) '

[opa]
symbol = "opa "
format = '\([$symbol($version)]($style)\) '

[os]
format = '\([$symbol]($style)\)'
disabled = false

[os.symbols]
Alpaquita = "alpaquita"
Alpine = "alpine"
Amazon = "amazon"
Android = "android"
Arch = "arch"
Artix = "artix"
CentOS = "cent"
Debian = "debian"
DragonFly = "dragonfly"
Emscripten = "emscripten"
EndeavourOS = "endevaour"
Fedora = "fedora"
FreeBSD = "freebsd"
Garuda = "garuda"
Gentoo = "gentoo"
HardenedBSD = "hardenedbsd"
Illumos = "illum"
Linux = "linux"
Mabox = "mabox"
Macos = "mac"
Manjaro = "manjaro"
Mariner = "mariner"
MidnightBSD = "midnightbsd"
Mint = "mint"
NetBSD = "netbsd"
NixOS = "nix"
OpenBSD = "openbsd"
OpenCloudOS = "opencloudos"
openEuler = "openeuler"
openSUSE = "opensuse"
OracleLinux = "oracle"
Pop = "pop"
Raspbian = "raspbian"
Redhat = "redhat"
RedHatEnterprise = "redhatent"
Redox = "redox"
Solus = "solus"
SUSE = "suse"
Ubuntu = "ubuntu"
Unknown = "unknown"
Windows = "windows"

[package]
symbol = "package "
format = '\([$symbol$version]($style)\) '

[perl]
symbol = "perl "
format = '\([$symbol$version]($style)\) '

[php]
symbol = "php "
format = '\([$symbol$version]($style)\) '

[pijul_channel]
symbol = "pijul "
format = '\([$symbol$channel]($style)\) '

[pulumi]
symbol = "pulumi "
format = '\([$symbol$stack]($style)\) '

[purescript]
symbol = "purescript "
format = '\([$symbol($version)]($style)\) '

[python]
symbol = "python "
format = '\([${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\) '

[raku]
symbol = "raku "
format = '\([$symbol($version-$vm_version)]($style)\) '

[red]
format = '\([$symbol($version)]($style)\) '

[ruby]
symbol = "ruby "
format = '\([$symbol($version)]($style)\) '

[rust]
symbol = "rust "
format = '\([$symbol($version)]($style)\) '

[scala]
symbol = "scala "
format = '\([$symbol($version)]($style)\) '

[spack]
symbol = "spack "
format = '\([$symbol$environment]($style)\) '

[solidity]
symbol = "solidity "
format = '\([$symbol($version)]($style)\) '

[sudo]
symbol = "sudo "
format = '\([as $symbol]($style)\) '

[swift]
symbol = "swift "
format = '\([$symbol($version)]($style)\) '

[terraform]
symbol = "terraform "
format = '\([$symbol$workspace]($style)\) '

[zig]
symbol = "zig "
format = '\([$symbol($version)]($style)\) '

[time]
format = '\([$time]($style)\)'
time_format = "%R"
disabled = false

[username]
format = '\([$user]($style)\)'
disabled = false
show_always = true
# format = "[$user]($style) on "
style_user = "bold #8be9fd"

[hostname]
ssh_symbol = 'ssh '
format = '\([$ssh_symbol$hostname]($style)\)'
disabled = false
style = "bold #bd93f9"

[vagrant]
format = '\([$symbol($version)]($style)\) '

[vlang]
symbol = "v "
format = '\([$symbol($version)]($style)\) '

# [palettes.catppuccin_macchiato]
# rosewater = "#f4dbd6"
# flamingo = "#f0c6c6"
# pink = "#f5bde6"
# mauve = "#c6a0f6"
# red = "#ed8796"
# maroon = "#ee99a0"
# peach = "#f5a97f"
# yellow = "#eed49f"
# green = "#a6da95"
# teal = "#8bd5ca"
# sky = "#91d7e3"
# sapphire = "#7dc4e4"
# blue = "#8aadf4"
# lavender = "#b7bdf8"
# text = "#cad3f5"
# subtext1 = "#b8c0e0"
# subtext0 = "#a5adcb"
# overlay2 = "#939ab7"
# overlay1 = "#8087a2"
# overlay0 = "#6e738d"
# surface2 = "#5b6078"
# surface1 = "#494d64"
# surface0 = "#363a4f"
# base = "#24273a"
# mantle = "#1e2030"
# crust = "#181926"

[cmd_duration]
style = "bold #f1fa8c"

