# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: "blahaj"
    replace: "blåhaj"
  - trigger: "Blahaj"
    replace: "Blåhaj"
  - trigger: "BLAHAJ"
    replace: "BLÅHAJ"
  - trigger: "!!"
    replace: "‼"
  - trigger: "??"
    replace: "⁇"
  - trigger: "?!"
    replace: "⁈"
  - trigger: "!?"
    replace: "⁉"
  - trigger: ":ss"
    replace: "ß"
  - trigger: ":SS"
    replace: "ẞ"

  - trigger: ":euro"
    replace: "€"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
    - name: mydate
      type: date
      params:
        format: "%d.%m.%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
    - name: output
      type: shell
      params:
        cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/

  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"
  - trigger: ":shock"
    replace: "ಠ_ಠ"
  - triggers:
    - ":tableflip"
    - ":fliptable"
    replace: "(╯°□°）╯︵ ┻━┻"
  - trigger: ":fixtable"
    replace: "┬─┬ノ( º _ ºノ)"

  - trigger: ":bar"
    replace: "—"
  - trigger: ":dash"
    replace: "–"

  - trigger: ":ae"
    replace: "æ"
  - trigger: ":oe"
    replace: "œ"
  - trigger: ":AE"
    replace: "Æ"
  - trigger: ":OE"
    replace: "Œ"

  - trigger: "mfg"
    replace: "Mit freundlichen Grüssen"
  # - trigger: "yt "
  #   replace: "YouTube "
  # - trigger: "dcord "
  #   replace: "Discord "
  - trigger: "hwo "
    replace: "how "
  - trigger: "thr "
    replace: "the "
  - trigger: "taht "
    replace: "that "
  - trigger: "taht's "
    replace: "that's "
  - trigger: "tpye "
    replace: "type "
  - trigger: "1st"
    replace: "1ˢᵗ"
  - trigger: "2nd"
    replace: "2ⁿᵈ"
  - trigger: "3rd"
    replace: "3ʳᵈ"
  - trigger: ":th "
    replace: "ᵗʰ "
  # - trigger: "imgs "
  #   replace: "images "
  # - trigger: "ppl "
  #   replace: "people "
  # - trigger: "be4 "
  #   replace: "before "
  # - trigger: "imo "
  #   replace: "in my opinion "
  # - trigger: "wb "
  #   replace: "welcome back "
  # - trigger: "alr "
  #   replace: "all right "
  # - trigger: "wym "
  #   replace: "What do you mean?"
  # - trigger: "idk "
  #   replace: "I don't know "
  # - trigger: "afaik "
  #   replace: "as far as i know "
  # - trigger: "iirc "
  #   replace: "if i recall correctly "

  - trigger: ":check"
    replace: "✓"
  - triggers:
    - ":yes"
    - ":bcheck"
    - ":boldcheck"
    - ":echeck"
    - ":emojicheck"
    replace: "✔"
  - trigger: ":x "
    replace: "×"
  - triggers:
    - ":no "
    - ":bx"
    - ":boldx"
    - ":ex "
    - ":emojix"
    replace: "❌"
  - triggers:
    - ":bolt"
    - ":zig"
    replace: "⚡"
  - trigger: ":warn"
    replace: "⚠️"
  - triggers:
    - ":xd"
    - ":xD"
    - ":Xd"
    - ":XD"
    replace: "😆"
  - triggers:
    - ":xp"
    - ":xP"
    - ":Xp"
    - ":XP"
    replace: "😝"
  - trigger: ":+1"
    replace: "👍"
  - trigger: ":star"
    replace: "🌟"
  - trigger: ":spark"
    replace: "✨"
  - trigger: "=D"
    replace: "😃"
  - triggers:
    - ":fallingstar"
    - ":starfalling"
    - ":meteor"
    - ":comet"
    replace: "🌠"
  - trigger: ":hex"
    replace: "⬡"
  - triggers:
    - ":bhex"
    - ":fhex"
    - ":hexf"
    - ":boldhex"
    - ":fillhex"
    - ":hexbold"
    - ":hexfill"
    replace: "⬢"

  - triggers:
    - ":dots"
    - "..."
    replace: "…"
  - trigger: ":<<"
    replace: "«"
  - trigger: ":>>"
    replace: "»"
  - trigger: ":> "
    replace: "› "
  - trigger: ":< "
    replace: "‹"
  - trigger: ":>,"
    replace: "›,"
  - trigger: ":>."
    replace: "›."
  - trigger: ":,,"
    replace: "„"
  - trigger: ":''"
    replace: "“"
  - trigger: ":\""
    replace: "”"
  - triggers:
    - ":bull"
    - ":bullet"
    replace: "•"
  - triggers:
    - ":tri"
    - ":triangle"
    replace: "‣"

  - trigger: ":copy"
    replace: "©"
  - trigger: ":reg"
    replace: "®"
  - trigger: ":trade"
    replace: "™"

  # Maths
  - trigger: ":xor"
    replace: "⊕"
  - trigger: ":sim "
    replace: "≈"
  - trigger: ":simeq"
    replace: "≃"
  - trigger: ":cong"
    replace: "≅"
  - trigger: ":partial"
    replace: "∂"
  - trigger: ":mdot"
    replace: "·"
  - trigger: ":nabla"
    replace: "∇"
  - trigger: ":int"
    replace: "∫"
  - trigger: ":sum"
    replace: "∑"
  - trigger: ":prod"
    replace: "∏"
  - trigger: ":ring"
    replace: "∘"
  - trigger: ":times"
    replace: "×"
  - trigger: ":div"
    replace: "÷"
  - trigger: ":cdot"
    replace: "‧"
  - trigger: ":pm"
    replace: "±"
  - trigger: ":land"
    replace: "∧"
  - trigger: ":lor"
    replace: "∨"
  - trigger: ":cap"
    replace: "∩"
  - trigger: ":cup"
    replace: "∪"
  - trigger: ":exists"
    replace: "∃"
  - trigger: ":nexists"
    replace: "∄"
  - trigger: ":forall"
    replace: "∀"
  - trigger: ":in "
    replace: "∈"
  - trigger: ":nin"
    replace: "∉"
  - trigger: ":infty"
    replace: "∞"
  - trigger: ":approx"
    replace: "≈"
  - trigger: ":if "
    replace: "→"
  - trigger: ":to "
    replace: "→ "
  - trigger: ":nif "
    replace: "↛"
  - trigger: ":iff"
    replace: "↔"
  - trigger: ":niff"
    replace: "↮"
  - trigger: ":def"
    replace: "≝"
  - trigger: ":leq"
    replace: "≤"
  - trigger: ":geq"
    replace: "≥"
  - trigger: ":neq"
    replace: "≠"
  - trigger: ":eq?"
    replace: "≟"
  - trigger: ":?="
    replace: "≟"
  - trigger: ":=?"
    replace: "≟"
  - trigger: ":eqals?"
    replace: "≟"
  - trigger: ":eqiv"
    replace: "≡"
  - trigger: ":mod"
    replace: "≡"
  - trigger: ":subset "
    replace: "⊂"
  - trigger: ":subseteq"
    replace: "⊆"
  - trigger: ":nsubset "
    replace: "⊄"
  - trigger: ":nsubseteq"
    replace: "⊈"
  - triggers:
    - ":varnothing"
    - ":empty"
    - ":{}"
    replace: "⌀"

  # Arrows
  - trigger: ":left "
    replace: "← "
  - trigger: ":right "
    replace: "→ "
  - trigger: ":up "
    replace: "↑ "
  - trigger: ":down "
    replace: "↓ "
  - triggers:
    - ":noleft "
    - ":notleft "
    replace: "↚ "
  - triggers:
    - ":noright "
    - ":notrright "
    replace: "↛ "
  - triggers:
    - ":leftright "
    - ":rightleft "
    replace: "↔ "
  - triggers:
    - ":updown "
    - ":downup "
    replace: "↕ "
  - triggers:
    - ":noleftright "
    - ":notleftright "
    replace: "↮ "

  # Double arrows
  - trigger: ":Left "
    replace: "⇐ "
  - trigger: ":Right "
    replace: "⇒ "
  - trigger: ":Up "
    replace: "⇑ "
  - trigger: ":Down "
    replace: "⇓ "
  - triggers:
    - ":noLeft "
    - ":notLeft "
    replace: "⇍ "
  - triggers:
    - ":noRight "
    - ":notRight "
    replace: "⇏ "
  - triggers:
    - ":Leftright "
    - ":LeftRight "
    replace: "⇔ "
  - triggers:
    - ":Updown "
    - ":UpDown "
    - ":Downup "
    - ":DownUp "
    replace: "⇕ "
  - triggers:
    - ":notLeftright "
    - ":notLeftRight "
    - ":noLeftright "
    - ":noLeftRight "
    replace: "⇎ "

  # Long arrows
  - trigger: ":longleft "
    replace: "⟵ "
  - trigger: ":longright "
    replace: "⟶ "
  - trigger: ":longleftright "
    replace: "⟷ "
  - trigger: ":longLeft "
    replace: "⟸ "
  - trigger: ":longRight "
    replace: "⟹ "
  - trigger: ":longLeftRight "
    replace: "⟺ "

  # Maps
  - trigger: ":mapsto"
    replace: "↦"
  - trigger: ":longmapsto"
    replace: "⟼"
  - trigger: ":Mapsto"
    replace: "⤇"
  - trigger: ":longMapsto"
    replace: "⟾"

  - trigger: ":=>>"
    replace: "➾"
  - triggers:
    - ":conflict"
    - ":zap"
    replace: "⚡"

